version: '3.8'

services:
  db:
    container_name: test-postgres
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
    ports:
      - '5555:5555'
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5555
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres: